### ISSUE TITLE
Add Windows XP support

### ISSUE THREAD

**Issue by LeMS-Studio5** [yoshiask/ZuneModdingHelper#1]
I am very happy that someone is taking the effort to bring new life to one of Microsoft's greatest, yet forgotten product lines. I was wondering if it would add support for Windows XP? I know XP is considered dead, but its the only Windows computer I have now (All my other computers are running some variant of Linux).  If it would be too much of a hassle, I could see about setting up a Windows 7 VM on one of my Linux Mint computers.

**Comment by yoshiask** [comment]
Unfortunately, this tool uses a lot of features that require .NET 5 to work. The last version of .NET that supports Windows XP/Vista/7  is 4, which doesn't sound too bad until you realize that .NET 4 was released in 2008. WinXP support can't happen unless I backport all of my dependencies to .NET 4, which may or may not be possible. I'll see what I can do down the line, but for now, you'll need Windows 8.1 or newer. Sorry!
